# 微信支付，以下参数均为虚构
wechat:
  pay:
    v3:
      # 租户id
      mobile:
        # 应用appId 必填
        app-id: wx554b6b******54312
        # api 密钥 可不填 目前V3没什么用
        app-secret: felordcn
        # api v3 密钥 必填
        app-v3-secret: 0e4efac*************5303ec
        # 微信支付商户号 必填
        mch-id: 1123****9
        # 商户服务器域名 用于回调  回调路径为 domain + notifyUrl  需要放开回调接口的安全策略 必填
        domain: https://felord.cn
        # 商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
        cert-path: wechat/apiclient_cert.p12

# 支付宝支付配置，以下为沙盒环境，正式环境请使用真实的线上配置。沙盒中证书参考 alipay-sandbox 文件夹下的配置
ali:
  pay:
    v1:
      app-id: 2016102700769563
      app-private-key-path: alipay-sandbox/app_rsa
      alipay-public-cert-path: alipay-sandbox/alipayCertPublicKey_RSA2.crt
      alipay-root-cert-path: alipay-sandbox/alipayRootCert.crt
      app-cert-public-key-path: alipay-sandbox/appCertPublicKey_2016102700769563.crt
      # 沙盒测试网关  正式请移除server-url 配置即可
      server-url: https://openapi.alipaydev.com/gateway.do;